# /opt/docker-gameServers.yml
---
version: '2.4'
services:
  minecraft:
      container_name: mc
      image: itzg/minecraft-server
      ports:
        - 25565:25565
      volumes:
        - /opt/appdata/mc:/data
      environment:
        EULA: 'true'
        MEMORY: 3G
        TZ: ${TZ}
        PLAYER_IDLE_TIMEOUT: 30
        DIFFICULTY: hard
        OPS: ${ME}
        MOTD: Join Discord @ Hollywoo Gaming, powered by Docker!
      tty: true
      stdin_open: true
      restart: always

  factorio:
    container_name: factorio
    image: factoriotools/factorio:stable
    ports:
    - 34197:34197/udp
    volumes:
    - /opt/appdata/factorio:/factorio
    restart: always

  starbound:
    container_name: starbound
    image: lacsap/starbound
    ports:
    - 21025:21025
    environment:
      - STEAM_USERNAME=${STUSER}
      - STEAM_PASSWORD=${STPASS}
    volumes:
    - /opt/appdata/starbound:/server/steamcmd/starbound
    restart: always
