# /opt/docker-compose.yml
---
version: '3.4'
services:
  plex:
    container_name: plex-beast
    image: plexinc/pms-docker
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  
  plexpy:
    container_name: plexpy-beast
    image: linuxserver/plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}


  minecraft:
    container_name: mc-beast
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "/mnt/disk1/mc:/data"
    environment:
      - EULA='true'
      - OVERRIDE_SERVER_PROPERTIES='true'
      - PLAYER_IDLE_TIMEOUT=60
      - MEMORY=4G
      - SPAWN_PROTECTION=3
      - OPS=${OPS}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - DIFFICULTY=${DIFFICULTY}
      - SEED=${SEED}
      - MOTD=Join Discord @ Hollywoo Gaming, powered by Docker
    tty: true
    stdin_open: true
    restart: always


  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env_file:
      - ../pass.env
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=$
    volumes:
      - '/opt/appdata/etc-pihole/:/etc/pihole/'
      - '/opt/appdata/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  # couchpotato:
  #   container_name: couchpotato
  #   image: linuxserver/couchpotato
  #   volumes:
  #     - /opt/appdata/couchpotato:/config
  #     - /mnt/disk2/downloads/couchpotato:/downloads
  #     - /mnt/disk3/movies:/movies
  #   ports:
  #     - 5050:5050
  #   env_file: docker-variables.env
  #   environment:
  #     - PUID
  #     - PGID
  #     - TZ
  #     - UMASK_SET
  #   restart: unless-stopped

  # transmission:
  #   container_name: transmission-beast
  #   image: linuxserver/transmission
  #   volumes:
  #     - /opt/appdata/transmission:/config
  #     - /mnt/disk2/downloads/transmission:/downloads
  #     - /mnt/storage/movies:/movies
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   environment:
  #     - PUID
  #     - PGID
  #     - TZ
  #   restart: unless-stopped
